id: P001814
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24826
  title: དབུས་གཙང་དམངས་གཞས་ལས་ཚེག་ཁྱིམ་དྲུག་མའི་ལས་ལ་དཔྱད་པ།
  author: ''
  volumes:
    91e5e84137de4bc593b160eec03ed910:
      image_group_id: I1KG24828
      title: ''
      volume_number: 1
      total_pages: 271
      base_file: v001.txt
