id: I1BC762AC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T11:41:01+00:00'
last_modified: '2022-06-07T15:14:58.108035+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24826
  title: དབུས་གཙང་དམངས་གཞས་ལས་ཚེག་ཁྱིམ་དྲུག་མའི་ལས་ལ་དཔྱད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    8D7A:
      image_group_id: I1KG24828
      title: ''
      total_pages: 271
      order: 1
      base_file: 8D7A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
